services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
    env_file: .env.local
    restart: unless-stopped
    environment:
      NODE_ENV: production
